# Generated by Django 3.2 on 2021-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cancel_order_for_money_back_cancel_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancel_order_for_money_back',
            options={'verbose_name_plural': 'Refund To Cancelled Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='Completed_order',
            field=models.BooleanField(default=False),
        ),
    ]
