# Generated by Django 3.2 on 2021-04-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('home', '0002_customer_more_information_emailconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Intructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor_information'),
        ),
    ]
