# Generated by Django 3.2 on 2021-04-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products_intructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer_more_information',
            options={'verbose_name_plural': 'More Customer Information'},
        ),
        migrations.AlterModelOptions(
            name='emailconfirmed',
            options={'verbose_name_plural': 'Email-Confirmed Users'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
